name: Testing

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:   # ✅ this enables "Run workflow" button in GitHub Actions tab

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build
